name: Deploy

on:
  push:
    tags: 
      - production 

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Website
      run: yarn deploy:website
    - name: Deploy App
      run: yarn deploy:app
