name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        yarn global add lerna
        lerna bootstrap
    - name: deploy app
      run: |
        cd packages/app
        yarn deploy
    - name: deploy website
      run: |
        cd packages/website
        yarn deploy
      env:
        CI: true
