name: Test

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn
    - name: Test App
      run: CI=true yarn test:app
    - name: Test Website
      run: CI=true yarn test:website
